# This file was generated by GoReleaser. DO NOT EDIT.
cask "agmux" do
  name "agmux"
  desc "Agent orchestration for tmux — manage AI coding agents across sessions"
  homepage "https://github.com/trentkm/agmux"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agmux"

  on_macos do
    on_intel do
      url "https://github.com/trentkm/agmux/releases/download/v#{version}/agmux_darwin_amd64.tar.gz"
      sha256 "916fa4cc535b1c64015bab2f61996d1897db054d3ecbe4bf9370ca81d3dbf427"
    end
    on_arm do
      url "https://github.com/trentkm/agmux/releases/download/v#{version}/agmux_darwin_arm64.tar.gz"
      sha256 "8fc8a1b2dc64d74b3fd9c519b7afa01da3c907c64da6d0c80f7f1d75eb8239c8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/trentkm/agmux/releases/download/v#{version}/agmux_linux_amd64.tar.gz"
      sha256 "3f4d4ffb056edf27bcbcaa8b3f4bc8698c3e6b8da45e760febb98124d5d81f67"
    end
    on_arm do
      url "https://github.com/trentkm/agmux/releases/download/v#{version}/agmux_linux_arm64.tar.gz"
      sha256 "24762f2b4b70dd201c708e572d3cfb62dfb9993a8bf51692fc493dc886e74f1f"
    end
  end

  # No zap stanza required
end
