# This file was generated by GoReleaser. DO NOT EDIT.
cask "agmux" do
  name "agmux"
  desc "Agent orchestration for tmux — manage AI coding agents across sessions"
  homepage "https://github.com/trentkm/agmux"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agmux"

  on_macos do
    on_intel do
      url "https://github.com/trentkm/agmux/releases/download/v#{version}/agmux_darwin_amd64.tar.gz"
      sha256 "a3f15ebeac3f536a5f83f735b7bf34bf09a7b023893c2aa5b1f7a332b3c133e9"
    end
    on_arm do
      url "https://github.com/trentkm/agmux/releases/download/v#{version}/agmux_darwin_arm64.tar.gz"
      sha256 "235b958f72d406d03981fdbbbb4dbcdda084d8645b379efec2e0168aa7e6ca53"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/trentkm/agmux/releases/download/v#{version}/agmux_linux_amd64.tar.gz"
      sha256 "6042919d4b8e492dbecd36c975cd5026101d57fae3745d0853aac7bba0377156"
    end
    on_arm do
      url "https://github.com/trentkm/agmux/releases/download/v#{version}/agmux_linux_arm64.tar.gz"
      sha256 "da7167b9ef7339b0105bcd7a49cdd7adaa5590cbfaa2eba8d4d35b33b37684de"
    end
  end

  # No zap stanza required
end
