# This file was generated by GoReleaser. DO NOT EDIT.
cask "agmux" do
  name "agmux"
  desc "Agent orchestration for tmux — manage AI coding agents across sessions"
  homepage "https://github.com/trentkm/agmux"
  version "0.5.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agmux"

  on_macos do
    on_intel do
      url "https://github.com/trentkm/agmux/releases/download/v#{version}/agmux_darwin_amd64.tar.gz"
      sha256 "0ef5b47d098b7a4c52e0d3058508cf8cfa89c7c284c20e7bb0e8bc09f32026d6"
    end
    on_arm do
      url "https://github.com/trentkm/agmux/releases/download/v#{version}/agmux_darwin_arm64.tar.gz"
      sha256 "87a659979a8c6a6e9b46f3b518cf9aec6ea049b67ab0b0ebd456f215729f943c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/trentkm/agmux/releases/download/v#{version}/agmux_linux_amd64.tar.gz"
      sha256 "8caef903ec87e2b58489d15f1581d771cc26dd25ab326d769f2e03310d811395"
    end
    on_arm do
      url "https://github.com/trentkm/agmux/releases/download/v#{version}/agmux_linux_arm64.tar.gz"
      sha256 "6a52c21bb9246f18304dfa885c65be0e0d923996e2cb3170bea94363980cf8d9"
    end
  end

  # No zap stanza required
end
