# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agmux < Formula
  desc "Agent orchestration for tmux — manage AI coding agents across sessions"
  homepage "https://github.com/trentkm/agmux"
  version "0.8.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/trentkm/agmux/releases/download/v0.8.0/agmux_darwin_amd64.tar.gz"
      sha256 "ce3c2af735b5b505cbe593edf1d3eb9c7cdde191bd6c32fb0fcddeb000693408"

      define_method(:install) do
        bin.install "agmux"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/trentkm/agmux/releases/download/v0.8.0/agmux_darwin_arm64.tar.gz"
      sha256 "9a65151207b50da1bf6530717193e0edb388d1bc81cb997fe5177000b20a331a"

      define_method(:install) do
        bin.install "agmux"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/trentkm/agmux/releases/download/v0.8.0/agmux_linux_amd64.tar.gz"
      sha256 "07b4e46e83b7d3a8bf8e7b6dc39c3079982117aa848fe8356b464b3797d17175"
      define_method(:install) do
        bin.install "agmux"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/trentkm/agmux/releases/download/v0.8.0/agmux_linux_arm64.tar.gz"
      sha256 "544998daaaa8cdf0b4a2d6fb3c15729743c34ed786e0ad02251a6ff01e5c3f46"
      define_method(:install) do
        bin.install "agmux"
      end
    end
  end
end
